# Site settings
title: alpha.omicron.seven
author:
  name: The Earl of Lydical
  email: lord@lydican.com
description: "Musings on Science & Progress, Technology & Medicine, Music & Mathematics"

# Build settings
remote_theme: rundocs/jekyll-rtd-theme
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

#exclude: .DS_Store